### ISSUE TITLE
ERROR  Cannot start nuxt:  nuxt.options.buildModules is not iterable 17:08:35

### ISSUE THREAD

**Issue by prashantnirgun** [KHTangent/nuxt-vuetify-starter#5]
I just clone the repo found error 

``` ERROR  Cannot start nuxt:  nuxt.options.buildModules is not iterable 17:08:35

  at initNuxt (node_modules/nuxt/dist/index.mjs:1353:21)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6779:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6840:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)
```

I try to upgrade the package then it give following error
```ERROR  Cannot start nuxt:  (0 , _nuxt.defineNuxtConfig) is not a function

  at nuxt.config.ts:4:43
  at Object.jiti (node_modules/jiti/dist/jiti.js:1:248468)
  at resolveConfig (node_modules/c12/dist/index.mjs:222:24)
  at loadConfig (node_modules/c12/dist/index.mjs:105:40)
  at async loadNuxtConfig (node_modules/@nuxt/kit/dist/index.mjs:446:18)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:1835:19)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:493:19)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6768:23)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6840:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)
```

**Comment by KHTangent** [comment]
The repo seemed broken for me too, I should probably have updated things sooner. It works for me now, maybe it works for you too?

**Comment by KHTangent** [comment]
Closing this, as it seems to work now. Feel free to re-open if the issue persists
